from flask_appbuilder.security.manager import AUTH_DB

SECRET_KEY = "CHANGE_ME_SUPERSET_SECRET_KEY"
SQLALCHEMY_TRACK_MODIFICATIONS = False

FEATURE_FLAGS = {
    "EMBEDDED_SUPERSET": True,
}

GUEST_ROLE_NAME = "Public"
GUEST_TOKEN_JWT_SECRET = "CHANGE_ME_GUEST_TOKEN_JWT_SECRET"
GUEST_TOKEN_JWT_ALGO = "HS256"
GUEST_TOKEN_JWT_EXP_SECONDS = 300

ENABLE_PROXY_FIX = True
TALISMAN_ENABLED = False

WTF_CSRF_ENABLED = True
WTF_CSRF_TIME_LIMIT = None

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True

AUTH_TYPE = AUTH_DB

PUBLIC_ROLE_LIKE = "Gamma"

ALLOWED_CORS_ORIGINS = [
    "https://app.example.com",
]

HTTP_HEADERS = {
    "X-Frame-Options": "ALLOWALL",
}

OVERRIDE_HTTP_HEADERS = {
    "X-Frame-Options": "ALLOWALL",
}